services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy  # Clearly specifies which Dockerfile to use
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
